version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      - DB_HOST=db
      - DB_NAME=your_database
      - DB_USER=your_username
      - DB_PASS=your_password
    depends_on:
      - db

# volumes:
#   postgres_data:
